spring:
   profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
      name: springcloudconfig-test-devv
---
spring:
 profiles: default
 application:
      name: springcloudconfig-test-default